spring.application.name=careplan-service

server.port=8093

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/medisphere

# Prediction Service
prediction.service.url=http://localhost:8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true